# -*- coding: utf-8 -*-
"""assignment4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HjZACkGHtHBMI_gyxqn166CYVbeq4xd-

1.1 Write a Python Program(with class concepts) to find the area of the triangle using the below
formula.
area = (s*(s-a)*(s-b)*(s-c)) ** 0.5
"""

#1.1
class length:
    def ilength(self):
        self.a=int(input("enter the side 1  "))
        self.b=int(input("enter the side 2  "))
        self.c=int(input("enter the side 3  "))

class triangle_area(length):
    def findarea(self):
        a,b,c=self.a,self.b,self.c
        s=(a+b+c)/2
        area=(s*(s-a)*(s-b)*(s-c))**0.5
        print(area)

t=triangle_area()
t.ilength()
t.findarea()

"""1.2 Write a function filter_long_words() that takes a list of words and an integer n and returns
the list of words that are longer than n.
"""

#1.2
l1=[]
def filter_long_words(l,n):
    for i in l:
        if(len(i)>n):
            l1.append(i)
    print(l1)

l=["hello","world","python","is","a ","programming","language"]
n=int(input("enter the integer "))
filter_long_words(l,n)

"""2.1 Write a Python program using function concept that maps list of words into a list of integers
representing the lengths of the corresponding words.
Hint: If a list [ ab,cde,erty] is passed on to the python function output should come as [2,3,4]
Here 2,3 and 4 are the lengths of the words in the list.
"""

l1=[]
def map_len(l):
    for i in l:
        l1.append(len(i))
    print(l1)
l=["hello","world","python","is","a","programming","language"]
print(l)
map_len(l)

"""2.2 Write a Python function which takes a character (i.e. a string of length 1) and returns True if
it is a vowel, False otherwise.
"""

def funct():
    ch=input("enter a character")
    if len(ch)>1:
        print("only character")
    else:
        if(ch=="a" and ch=="e" and ch=="i" and ch=="o" and ch=="u"):
            print("True")
        else:
            print("False")
funct()